Repository MONEYMONG/iOS-Moneymong, pull requests merged in 2024-12, with the labels that each got.

#82 [D-0] 소속 검색 기능구현
  Projects/App/Sources/AppCoordinator.swift
  Projects/Core/Core/Sources/Network/APIs/AgencyAPI/Repository/AgencyAPI.swift
  Projects/Core/Core/Sources/Network/APIs/AgencyAPI/Repository/AgencyRepository.swift
  Projects/Core/Core/Sources/Network/Common/NetworkManager.swift
  Projects/Core/Core/Sources/Network/Common/TokenRequestIntercepter.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListReactor.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/SearchView.swift
  Projects/Feature/Main/Sources/MainTabBarCoordinator.swift
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Feature/MyPage/Sources/Common/MyPageCoordinator.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignCoordinator.swift
  Projects/Shared/DesignSystem/Demo/Sources/ViewControllers/AlertVC.swift
  Projects/Shared/DesignSystem/Demo/Sources/ViewControllers/SnackBarVC.swift
  Projects/Shared/DesignSystem/Sources/SnackBar/SnackBarManager.swift
  Projects/Shared/DesignSystem/Sources/Utils/UIViewController+.swift
Labels: 기능

#83 [D-1] Network Logger 구현 (539)
  Projects/Core/Core/Sources/Network/APIs/SignAPI/Repository/SignRepository.swift
  Projects/Core/Core/Sources/Network/APIs/UniversityAPI/Repository/UniversityRepository.swift
  Projects/Core/Core/Sources/Network/Common/NetworkLogger.swift
  Projects/Core/Core/Sources/Network/Common/NetworkManager.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignDIContainer.swift
Labels: 기능

#86 [D-0] hotfix capture Session 백그라운드 스레드에서 동작하도록 수정
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/Components/CameraView.swift
Labels: 수정

#87 [D-1] network&storage mocking
  .package.resolved
  Projects/Core/Core/Project.swift
  Projects/Core/Core/Sources/Network/APIs/SignAPI/Entity/SignInfo.swift
  Projects/Core/Core/Sources/Network/APIs/SignAPI/Repository/SignRepository.swift
  Projects/Core/Core/Sources/Network/APIs/SignAPI/ResponseDTO/SignResponseDTO.swift
  Projects/Core/Core/Sources/Network/APIs/UniversityAPI/Entity/Universities.swift
  Projects/Core/Core/Sources/Network/APIs/UniversityAPI/Repository/UniversityRepository.swift
  Projects/Core/Core/Sources/Network/APIs/UniversityAPI/ResponseDTO/UniversityResponseDTO.swift
  Projects/Core/Core/Sources/Network/APIs/UserAPI/Repository/UserRepository.swift
  Projects/Core/Core/Sources/Network/APIs/UserAPI/ResponseDTO/UserResponseDTO.swift
  Projects/Core/Core/Testing/MockLocalStorage.swift
  Projects/Core/Core/Testing/MockNetworkManager.swift
  Projects/Domain/Auth/Interface/AutoSignUseCaseInterface.swift
  Projects/Domain/Auth/Interface/DeleteUserUseCaseInterface.swift
  Projects/Domain/Auth/Interface/Entity/LoginType.swift
  Projects/Domain/Auth/Interface/Entity/SignInfo.swift
  Projects/Domain/Auth/Interface/LogoutUseCaseInterface.swift
  Projects/Domain/Auth/Interface/SignUpUseCaseInterface.swift
  Projects/Domain/User/Interface/Entity/University.swift
  Projects/Domain/User/Interface/Entity/UserInfo.swift
  Projects/Domain/User/Interface/GetMyInfoUseCaseInterface.swift
  Projects/Domain/User/Interface/SearchUniversitiesUseCaseInterface.swift
  Projects/Domain/User/Project.swift
  Projects/Domain/User/Tests/GetMyInfoUseCaseTests.swift
  Projects/Domain/User/Tests/UserTests.swift
  Projects/Feature/Agency/Project.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListReactor.swift
  Projects/Feature/CreateAgency/Project.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputUniversityInfo/Components/GradeInputView.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputUniversityInfo/Components/UniversityCell.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputUniversityInfo/InputUniversityInfoReactor.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputUniversityInfo/InputUniversityInfoVC.swift
  Projects/Feature/MyPage/Project.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/Model/MypageSectionItemModel.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/MyPageReactor.swift
  Projects/Feature/Sign/Project.swift
  Projects/Feature/Sign/Sources/Scene/Login/LoginReactor.swift
Labels: 기능, 수정
