Repository MONEYMONG/iOS-Moneymong, pull requests merged in 2024-06, with the labels that each got.

#44 [D- 0] 운영비 등록화면에서 keyboard dismiss 기능 추가(401), 장부 empty 화면 UI 수정(402)
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/Components/LedgerListEmptyView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/MyPage/Sources/Scene/Withdrawal/WithdrawalVC.swift
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/scan.phone.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/scan.phone.imageset/Phone_Scan.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/scan.phone.imageset/Phone_Scan@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/scan.phone.imageset/Phone_Scan@3x.png
  Projects/Shared/DesignSystem/Sources/Utils/Images.swift
Labels: 기능

#43 [D-0] - 앱이름변경(398), 개인정보처리방침 링크변경(399), 소속 스크롤시 네비에기션 영역과 겹치는문제 수정(400)
  Projects/App/Project.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/MyPageVC.swift
Labels: 기능

#46 [D-1] scrollView contentInset를 활용해 키보드 높이 처리 408
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
Labels: 수정

#47 [D-1] 장부 등록 화면 수정 - 409,410
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
Labels: 수정

#48 [D-0] UI수정 411 412 418 419 420 421
  Projects/Core/LocalStorage/Sources/LocalStorage/LocalStorageKey.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/Entity/Member.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/Repository/AgencyAPI.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/RequestDTO/ChangeMemberRoleRequestDTO.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/RequestDTO/KickoutMemberRequestDTO.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/ResponseDTO/AgencyMemberListResponseDTO.swift
  Projects/Feature/Agency/Sources/AgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/AgencyCell.swift
  Projects/Feature/Agency/Sources/Scene/CreateAgency/CreateAgencyVC.swift
  Projects/Feature/Agency/Sources/Scene/CreateComplete/CreateCompleteVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/Components/AgencyCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/AssignRoleView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/MemberCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/MemberEmptyView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/MyProfileView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabVC.swift
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Shared/DesignSystem/Demo/Sources/ViewControllers/TagVC.swift
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.group.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.group.imageset/img_club.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.group.imageset/img_club@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.group.imageset/img_club@3x.png
  Projects/Shared/DesignSystem/Sources/Buttons/FloatingButton.swift
  Projects/Shared/DesignSystem/Sources/Tag/TagView.swift
  Projects/Shared/DesignSystem/Sources/Utils/Images.swift
Labels: 기능

#49 [D-1] DatePicker Custom(394), 장부 리스트 UI 수정(416)
  Projects/Feature/Ledger/Sources/Common/DIContainer/LedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/CreateManualLedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/CreateOCRLedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/DatePickerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/DatePickerSheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/DateCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/MMDatePicker.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/MMPicker.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/Components/LedgerCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Shared/DesignSystem/Sources/Utils/Colors.swift
Labels: 기능, 수정

#51 [D-1] Qa/423 422 417 427
  Projects/Core/Network/Sources/APIs/SignAPI/Repository/SignRepository.swift
  Projects/Feature/Base/Sources/Reactive+.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsView.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Sign/Sources/Scene/Login/LoginReactor.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashReactor.swift
Labels: 기능

#52 [D-0] 워딩변경 및 회원가입시 학년선택 과정에서 오류 수정 (426, 428, 430, 438, 439, 440, 441, 442)
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/Components/GradeInputView.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpVC.swift
  Projects/Shared/DesignSystem/Sources/Buttons/MMSegmentControl.swift
Labels: 기능

#50 [D-0] 424 425 429 431 432 435 436 티켓수정
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/CreateAgency/CreateAgencyVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinAgency/JoinAgencyVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignCoordinator.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpVC.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashVC.swift
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.congrats.imageset/img_congrats.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.congrats.imageset/img_congrats@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/MoneyMong/mong.congrats.imageset/img_congrats@3x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/ic_warning.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/ic_warning@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/ic_warning@3x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/status=filled.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/status=filled@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/Warning/warning.fill.imageset/status=filled@3x.png
  Projects/Shared/DesignSystem/Sources/SnackBar/MMSnackBar.swift
Labels: 기능

#53 [D-1] UI 수정 414 433 434 437 444 445
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/AgencyCell.swift
  Projects/Feature/Agency/Sources/Scene/CreateComplete/CreateCompleteVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinComplete/JoinCompleteVC.swift
  Projects/Feature/Base/Sources/UINavigationController+.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Shared/DesignSystem/Sources/TextFields/MMTextView.swift
Labels: 수정

#54 [D-0] 447 449
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/AssignRoleView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/EditMember/EditMemberSheetVC.swift
Labels: 기능

#55 [D-0] 장부 및 소속 Cell, 네이게이션 소속 라벨 일정 너비를 초과 시 생략(448)
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/AgencyCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/DatePickerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/MMPicker.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/Components/AgencyCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/Components/LedgerCell.swift
Labels: 수정

#56 [D-0] 회원가입 - 학년 선택 안했는데 버튼이 활성화됨 - 452
  Projects/Feature/Sign/Sources/Scene/SignUp/Components/GradeInputView.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpReactor.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpVC.swift
Labels: 기능

#59 [D-0] 453 454 456 459 460 462
  Projects/Core/Network/Sources/APIs/AgencyAPI/Entity/Agency.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/Repository/AgencyAPI.swift
  Projects/Core/Network/Sources/APIs/AgencyAPI/ResponseDTO/AgencyListResponseDTO.swift
  Projects/Core/Network/Sources/APIs/UniversityAPI/Entity/University.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/AgencyCell.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/Components/LedgerListEmptyView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/EditMember/EditMemberSheetVC.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/Cell/UniversityCell.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/MyPageVC.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/Components/EmptyListView.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/Components/GradeInputView.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/Components/UniversityCell.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpVC.swift
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/Contents.json
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/ic_search.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/ic_search@2x.png
  Projects/Shared/DesignSystem/Resources/Image/Icon.xcassets/search.imageset/ic_search@3x.png
  Projects/Shared/DesignSystem/Sources/TextFields/MMSearchBar.swift
Labels: 기능

#57 [D-1] 장부 수동작성 이슈 수정 458 461 468
  Projects/Feature/Base/Sources/Reactive+.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpVC.swift
  Projects/Shared/DesignSystem/Sources/TextFields/MMTextField.swift
Labels: 수정

#60 [D-0] 마이몽 Cell Separator Inset 수정 - 475
  Projects/Feature/MyPage/Sources/Scene/MyPage/MyPageVC.swift
Labels: 기능

#61 [D-0] UI 수정 464 469 470 473 474
  Projects/Core/Network/Sources/Common/MoneyMongError.swift
  Projects/Core/Network/Sources/Common/NetworkManager.swift
  Projects/Feature/Agency/Sources/Scene/JoinAgency/JoinAgencyVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/Components/CameraView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/MMDatePicker.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/DatePicker/Views/MMPicker.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpReactor.swift
  Projects/Shared/DesignSystem/Sources/Alerts/MMAlerts.swift
Labels: 수정

#65 [D-0] 장부 리스트 페이징 구현 및 에러 수정 (406 479 484)
  Projects/Core/Network/Sources/APIs/LedgerAPI/Entity/Ledger.swift
  Projects/Core/Network/Sources/APIs/LedgerAPI/Entity/LedgerList.swift
  Projects/Core/Network/Sources/APIs/LedgerAPI/Entity/OCRResult.swift
  Projects/Core/Network/Sources/APIs/LedgerAPI/ResponseDTO/LedgerListResponseDTO.swift
  Projects/Core/Network/Sources/APIs/LedgerAPI/ResponseDTO/OCRResponseDTO.swift
  Projects/Core/Network/Sources/Common/ErrorResponse.swift
  Projects/Core/Network/Sources/Common/MoneyMongError.swift
  Projects/Core/Network/Sources/Common/NetworkManager.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/Components/CameraView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Sign/Sources/Scene/SignUp/SignUpReactor.swift
Labels: 기능, 수정
