Repository MONEYMONG/iOS-Moneymong, pull requests merged in 2025-01, with the labels that each got.

#89 [D-3] Agency Domain 구현
  Projects/Core/Core/Project.swift
  Projects/Core/Core/Sources/Network/APIs/AgencyAPI/Repository/AgencyRepository.swift
  Projects/Core/Core/Sources/Network/APIs/AgencyAPI/ResponseDTO/AgencyListResponseDTO.swift
  Projects/Core/Core/Sources/Network/APIs/AgencyAPI/ResponseDTO/AgencyMemberListResponseDTO.swift
  Projects/Domain/Agency/Interface/ChangeMemberRoleUseCaseInterface.swift
  Projects/Domain/Agency/Interface/ConfirmCertificateCodeUseCaseInterface.swift
  Projects/Domain/Agency/Interface/CreateAgencyUseCaseInterface.swift
  Projects/Domain/Agency/Interface/DeleteAgencyUseCaseInterface.swift
  Projects/Domain/Agency/Interface/Entity/Agency.swift
  Projects/Domain/Agency/Interface/Entity/Member.swift
  Projects/Domain/Agency/Interface/GetAgencyListUseCaseInterface.swift
  Projects/Domain/Agency/Interface/GetInvitationCodeUseCaseInterface.swift
  Projects/Domain/Agency/Interface/GetMemberListUseCaseInterface.swift
  Projects/Domain/Agency/Interface/GetMyAgencyUseCaseInterface.swift
  Projects/Domain/Agency/Interface/KickoutMemberUseCaseInterface.swift
  Projects/Domain/Agency/Interface/ReissueCodeUseCaseInterface.swift
  Projects/Domain/Agency/Interface/SearchAgencyUseCaseInterface.swift
  Projects/Domain/Agency/Project.swift
  Projects/Domain/Agency/Sources/ChangeMemberRoleUseCase.swift
  Projects/Domain/Agency/Sources/ConfirmCertificateCodeUseCase.swift
  Projects/Domain/Agency/Sources/CreateAgencyUseCase.swift
  Projects/Domain/Agency/Sources/DeleteAgencyUseCase.swift
  Projects/Domain/Agency/Sources/GetAgencyListUseCase.swift
  Projects/Domain/Agency/Sources/GetInvitationCodeUseCase.swift
  Projects/Domain/Agency/Sources/GetMemberListUseCase.swift
  Projects/Domain/Agency/Sources/GetMyAgencyUseCase.swift
  Projects/Domain/Agency/Sources/KickoutMemberUseCase.swift
  Projects/Domain/Agency/Sources/ReissueCodeUseCase.swift
  Projects/Domain/Agency/Sources/SearchAgencyUseCase.swift
  Projects/Domain/Agency/Testing/Dummy.swift
  Projects/Domain/Agency/Tests/AgencyTests.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListReactor.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/Components/AgencyCell.swift
  Projects/Feature/Base/Project.swift
  Projects/Feature/Ledger/Sources/Common/DIContainer/LedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Common/LedgerCoordinator/LedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/Components/AgencyCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/AssignRoleView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/MemberCell.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/Components/MyProfileView.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/EditMember/EditMemberReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabVC.swift
  Projects/Feature/Ledger/Sources/Scene/Service/AgencyService.swift
Labels: 기능

#90 [D-1] Ledger Feature 의존성 주입 방식 변경
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domain/Agency/Interface/DeleteAgencyUseCaseInterface.swift
  Projects/Domain/Agency/Interface/KickoutMemberUseCaseInterface.swift
  Projects/Domain/Agency/Sources/DeleteAgencyUseCase.swift
  Projects/Domain/Agency/Sources/KickoutMemberUseCase.swift
  Projects/Domain/User/Interface/GetSelectedAgencyUseCaseInterface.swift
  Projects/Domain/User/Interface/GetUserIDUseCaseInterface.swift
  Projects/Domain/User/Interface/UpdateSelectedAgencyUseCaseInterface.swift
  Projects/Domain/User/Sources/GetSelectedAgencyUseCase.swift
  Projects/Domain/User/Sources/GetUserIDUseCase.swift
  Projects/Domain/User/Sources/UpdateSelectedAgencyUseCase.swift
  Projects/Domain/User/Tests/GetSelectedAgencyTests.swift
  Projects/Domain/User/Tests/GetUserIDUseCaseTests.swift
  Projects/Domain/User/Tests/UpdateSelectedAgencyUseCaseTests.swift
  Projects/Feature/Base/Sources/Common/DIContainer.swift
  Projects/Feature/Ledger/Interface/LedgerFactoryInterface.swift
  Projects/Feature/Ledger/Interface/ManualPresentType.swift
  Projects/Feature/Ledger/Project.swift
  Projects/Feature/Ledger/Sources/Common/DIContainer/LedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Common/LedgerCoordinator/ImagePickerPresentable.swift
  Projects/Feature/Ledger/Sources/Common/LedgerCoordinator/LedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Common/LedgerFactory.swift
  Projects/Feature/Ledger/Sources/Model/ContentFormatter.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/Components/LedgerContentsView/LedgerContentsView.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/CreateManualLedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/CreateManualLedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/CreateOCRLedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/CreateOCRLedgerDIContainer.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Sheets/SelectAgency/SelectAgencySheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/EditMember/EditMemberReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/EditMember/EditMemberSheetVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabVC.swift
  Projects/Feature/Ledger/Sources/Scene/Service/AgencyService.swift
  Projects/Feature/Ledger/Sources/Scene/Service/LedgerListService.swift
  Projects/Feature/Ledger/Sources/Scene/Service/LedgerService.swift
  Projects/Feature/Ledger/Sources/Scene/Service/MemberService.swift
  Projects/Feature/Ledger/Testing/Dummy.swift
  Projects/Feature/Main/Sources/MainDIContainer.swift
Labels: 수정

#92 [D-1] Sign & CreateAgency UseCase 적용 및 의존성 수정
  Projects/App/Sources/AppCoordinator.swift
  Projects/App/Sources/DIContainer.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Core/Core/Sources/Network/APIs/SignAPI/Repository/SignRepository.swift
  Projects/Core/Core/Sources/Network/APIs/TokenAPI/Repository/TokenRepository.swift
  Projects/Core/Core/Sources/Network/Common/TokenRequestIntercepter.swift
  Projects/Domain/Auth/Interface/AutoSignUseCaseInterface.swift
  Projects/Domain/Auth/Interface/GetRecentLoginInfoUseCaseInterface.swift
  Projects/Domain/Auth/Sources/AutoSignUseCase.swift
  Projects/Domain/Auth/Sources/GetRecentLoginInfoUseCase.swift
  Projects/Domain/User/Interface/RegisterUniversitiesUseCaseInterface.swift
  Projects/Domain/User/Sources/RegisterUniversitiesUseCase.swift
  Projects/Feature/Agency/Sources/AgencyDIContainer.swift
  Projects/Feature/CreateAgency/Interface/CreateAgencyCoordinator.swift
  Projects/Feature/CreateAgency/Project.swift
  Projects/Feature/CreateAgency/Sources/Factorys/CreateCompleteFactory.swift
  Projects/Feature/CreateAgency/Sources/Factorys/InputAgencyInfoFactory.swift
  Projects/Feature/CreateAgency/Sources/Factorys/InputUniversityInfoFactory.swift
  Projects/Feature/CreateAgency/Sources/Scene/CreateComplete/CreateCompleteReactor.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputAgencyInfo/InputAgencyInfoReactor.swift
  Projects/Feature/CreateAgency/Sources/Scene/InputUniversityInfo/InputUniversityInfoReactor.swift
  Projects/Feature/Ledger/Project.swift
  Projects/Feature/Main/Sources/MainDIContainer.swift
  Projects/Feature/Sign/Interface/SignFactoryInterface.swift
  Projects/Feature/Sign/Project.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignCoordinator.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignDIContainer.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignFactory.swift
  Projects/Feature/Sign/Sources/Scene/Login/LoginReactor.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashReactor.swift
  Projects/Feature/Sign/Testing/Dummy.swift
Labels: 기능, 수정

#94 [D-1] AgencyFeature에 UseCase 적용 및 의존성 수정
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domain/Agency/Interface/ConfirmCertificateCodeUseCaseInterface.swift
  Projects/Domain/Agency/Sources/ConfirmCertificateCodeUseCase.swift
  Projects/Feature/Agency/Interface/AgencyFactoryInterface.swift
  Projects/Feature/Agency/Project.swift
  Projects/Feature/Agency/Sources/AgencyDIContainer.swift
  Projects/Feature/Agency/Sources/Common/AgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Common/AgencyFactory.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListReactor.swift
  Projects/Feature/Agency/Sources/Scene/JoinAgency/JoinAgencyReactor.swift
  Projects/Feature/Agency/Testing/Dummy.swift
  Projects/Feature/Main/Sources/MainDIContainer.swift
Labels: 기능

#96 [D-0] Coordinator 구조 변경
  Projects/App/Sources/AppCoordinator.swift
  Projects/Feature/Agency/Sources/Common/AgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinAgency/JoinAgencyVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinComplete/JoinCompleteVC.swift
  Projects/Feature/Base/Project.swift
  Projects/Feature/Base/Sources/Coordinator.swift
  Projects/Feature/CreateAgency/Interface/CreateAgencyCoordinator.swift
  Projects/Feature/Ledger/Sources/Common/LedgerCoordinator/ImagePickerPresentable.swift
  Projects/Feature/Ledger/Sources/Common/LedgerCoordinator/LedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Detail/LedgerDetailVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/CreateManualLedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/CreateOCRLedgerCoordinator.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanCreater/CreateOCRLedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Member/MemberList/MemberTabVC.swift
  Projects/Feature/Main/Sources/MainDIContainer.swift
  Projects/Feature/Main/Sources/MainTabBarCoordinator.swift
  Projects/Feature/Main/Sources/MainTapViewController.swift
  Projects/Feature/MyPage/Sources/Common/MyPageCoordinator.swift
  Projects/Feature/MyPage/Sources/Scene/MyPage/MyPageVC.swift
  Projects/Feature/MyPage/Sources/Scene/Withdrawal/WithdrawalVC.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignCoordinator.swift
  Projects/Feature/Sign/Sources/Scene/Congratulations/CongratulationsVC.swift
  Projects/Feature/Sign/Sources/Scene/Login/LoginVC.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashVC.swift
Labels: 수정

#98 [D-1] Agency, Sign, JoinAgency, CreateAgency Coordinator Interface & Implement 구현
  Projects/App/Sources/SceneDelegate.swift
  Projects/Feature/Agency/Interface/AgencyCoordinatorInterface.swift
  Projects/Feature/Agency/Interface/AgencyFactoryInterface.swift
  Projects/Feature/Agency/Interface/CreateAgencyCoordinatorInterface.swift
  Projects/Feature/Agency/Interface/JoinAgencyCoordinatorInterface.swift
  Projects/Feature/Agency/Project.swift
  Projects/Feature/Agency/Sources/Common/AgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Common/AgencyFactory.swift
  Projects/Feature/Agency/Sources/Common/CreateAgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Common/JoinAgencyCoordinator.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Agency/Sources/Scene/InputAgencyInfo/InputAgencyInfoVC.swift
  Projects/Feature/Agency/Sources/Scene/InputUniversityInfo/InputUniversityInfoVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinAgency/JoinAgencyVC.swift
  Projects/Feature/Agency/Sources/Scene/JoinComplete/JoinCompleteVC.swift
  Projects/Feature/Main/Sources/MainDIContainer.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignCoordinator.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashVC.swift
Labels: 기능, 수정

#100 [D-0] Hotfix 앱 삭제 후 다시 실행 시 앱이 터지는 문제 해결
  Projects/App/Project.swift
  Projects/Core/Core/Sources/Cache/Cacheable.swift
  Projects/Core/Core/Sources/Cache/MemoryCache.swift
  Projects/Core/Core/Sources/Network/APIs/UserAPI/Repository/UserRepository.swift
  Projects/Core/Core/Sources/Network/Common/NetworkLogger.swift
  Projects/Core/Core/Sources/Network/Common/NetworkManager.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListReactor.swift
  Projects/Feature/Agency/Sources/Scene/AgencyList/AgencyListVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Manual/ManualCreater/CreateManualLedgerReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/Creaters/Scan/ScanResult/OCRResultReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/LedgerVC.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabReactor.swift
  Projects/Feature/Ledger/Sources/Scene/Ledger/TabItems/Ledger/LedgerTabVC.swift
  Projects/Feature/Sign/Sources/Scene/Common/SignDIContainer.swift
  Projects/Feature/Sign/Sources/Scene/Splash/SplashReactor.swift
Labels: 기능, 수정
